# Generated by Django 2.2.14 on 2021-02-01 07:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20210125_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('logged', models.BooleanField(default=False, help_text='If otp verification got successful')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('storeName', models.CharField(max_length=100)),
                ('productCategory', models.CharField(blank=True, choices=[('aa', 'Science Fiction'), ('bb', 'Romance'), ('cc', 'Kids'), ('dd', 'Youngster'), ('ee', 'Old age'), ('ff', 'Student'), ('gg', 'Motivation'), ('ii', 'Class 6'), ('jj', 'Class 7'), ('kk', 'Class 8'), ('ll', 'Class 9'), ('mm', 'Class 11'), ('nn', 'Class 12'), ('mm', 'NCERT')], max_length=1, null=True)),
                ('zip', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('GST', models.CharField(max_length=50)),
                ('tax_details', models.CharField(max_length=50)),
                ('provisionalGSTIN', models.CharField(max_length=100)),
                ('PAN_number', models.CharField(max_length=100)),
                ('Account_holder_name', models.CharField(max_length=100)),
                ('Account_type', models.CharField(blank=True, choices=[('Sacc', 'Savings Account'), ('Oacc', 'Overdraft Account'), ('Cacc', 'Current Account')], max_length=50, null=True)),
                ('Account_number', models.CharField(max_length=100)),
                ('ReEnter_account_number', models.CharField(max_length=100)),
                ('IFSC_code', models.CharField(max_length=100)),
                ('signature', models.ImageField(blank=True, default='Shreyash.jpg', upload_to='signature_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Seller_Profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SellerProfile'),
        ),
    ]
