# Generated by Django 2.2.14 on 2021-02-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210201_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of otp sent', null=True),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='logged',
            field=models.BooleanField(blank=True, default=False, help_text='If otp verification got successful', null=True),
        ),
    ]
