# Generated by Django 2.2.14 on 2021-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210201_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='terms_condition',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
