# Generated by Django 2.2.14 on 2021-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sellerprofile_terms_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
