# Generated by Django 2.2.14 on 2021-02-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210203_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='verified',
            field=models.BooleanField(blank=True, default=False, help_text='If otp verification got successful', null=True),
        ),
    ]
